---
- name: Clear dynamic MAC address table on Cisco Catalyst 9000
  hosts: 10.20.103.114
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Clear all dynamic MAC addresses
      cisco.ios.ios_command:
        commands:
          - clear mac address-table dynamic
      ignore_errors: yes
