---
- name: Clear dynamic MAC address table on Cisco Catalyst 9000
  hosts: cisco_catalyst_switches
  gather_facts: no
  vars:
    ansible_network_cli_ssh_type: paramiko

  tasks:
    - name: Clear all dynamic MAC addresses
      cisco.ios.ios_command:
        commands:
          - clear mac address-table dynamic
      ignore_errors: yes
          
     
