---
- name: Configure hostname and interface on Cisco ISR router
  hosts: cisco_catalyst_switches
  gather_facts: false
  connection: network_cli

  collections:
    - cisco.ios

  tasks:
    - name: Set switch hostname
      cisco.ios.ios_hostname:
        config:
          hostname: cisco-switch-055
        state: merged

   
