---
- name: Configure hostname and interface on Cisco ISR router
  hosts: cisco_catalyst_switches
  gather_facts: no

  collections:
    - cisco.ios

  tasks:
    - name: Set switch hostname
      cisco.ios.ios_config:
        lines:
          - hostname cisco-switch-05

    - name: Create VLANs
      cisco.ios.ios_config:
        lines:
          - name Sales
        parents: vlan 10

    - name: Configure access ports and assign VLANs
      cisco.ios.ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 10
          - no shutdown
        parents: interface FastEthernet0/5

    - name: Save running configuration
      cisco.ios.ios_config:
        save_when: modified

    - name: Get running configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: running_config

    - name: Print running configuration
      debug:
        msg: "{{ running_config.stdout[0] }}"

   
