---
- name: Create a VLAn in Cisco Catalyst switch
  hosts: cisco_catalyst_switches
  gather_facts: no

  collections:
    - cisco.ios

  tasks:
    - name: Set switch hostname
      cisco.ios.ios_config:
        lines:
          - hostname {{ SWITCH_NAME }}

    - name: Create VLANs
      cisco.ios.ios_config:
        lines:
          - name {{ VLAN_NAME }}
        parents: vlan {{ VLAN_ID }}

    - name: Get running configuration
      cisco.ios.ios_command:
        commands: show vlan
      register: vlans

    - name: Print VLANs in the switch
      debug:
        msg: "{{ vlans.stdout[0] }}"

   
